[project]
name = "magiccars-email-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-functions==1.23.0",
    "azure-keyvault-secrets==4.10.0",
    "openai==1.97.0",
    "python-dotenv==1.1.1",
]
